import clsx from 'clsx';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  variable: '--font-quicksand',
});

export const metadata: Metadata = {
  title: 'lazuardidev',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(quicksand.variable, 'antialiased')}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
